import type { MCQ } from '@/shared/types';

export const HARDCODED_MCQS: MCQ[] = [
  // ===================== CLASS 10 CBSE - MATHEMATICS (math_10) =====================
  {
    id: 'm10-001',
    exam: 'class_10_cbse',
    subject_id: 'math_10',
    chapter_id: 'math_10_ch1',
    difficulty: 'easy',
    question: 'What is the HCF of two consecutive even numbers?',
    option_a: '1',
    option_b: '2',
    option_c: '0',
    option_d: '4',
    correct_option: 'B',
    explanation: 'Any two consecutive even numbers can be written as 2n and 2n + 2. The greatest common factor of 2n and 2(n+1) is always 2.',
    tags: ['Real Numbers', 'HCF'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'm10-002',
    exam: 'class_10_cbse',
    subject_id: 'math_10',
    chapter_id: 'math_10_ch1',
    difficulty: 'medium',
    question: 'If HCF(306, 657) = 9, what is LCM(306, 657)?',
    option_a: '22338',
    option_b: '22339',
    option_c: '11338',
    option_d: '22438',
    correct_option: 'A',
    explanation: 'Using the property HCF × LCM = Product of two numbers: 9 × LCM = 306 × 657 ⇒ LCM = (306 × 657) / 9 = 22338.',
    tags: ['Real Numbers', 'LCM'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'm10-003',
    exam: 'class_10_cbse',
    subject_id: 'math_10',
    chapter_id: 'math_10_ch2',
    difficulty: 'easy',
    question: 'If one zero of the quadratic polynomial x² + 3x + k is 2, then the value of k is:',
    option_a: '10',
    option_b: '-10',
    option_c: '-7',
    option_d: '-2',
    correct_option: 'B',
    explanation: 'Substitute x = 2 into the polynomial: 2² + 3(2) + k = 0 ⇒ 4 + 6 + k = 0 ⇒ k = -10.',
    tags: ['Polynomials', 'Zeros'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'm10-004',
    exam: 'class_10_cbse',
    subject_id: 'math_10',
    chapter_id: 'math_10_ch3',
    difficulty: 'medium',
    question: 'If the lines given by 3x + 2ky = 2 and 2x + 5y + 1 = 0 are parallel, then the value of k is:',
    option_a: '15/4',
    option_b: '3/2',
    option_c: '4/15',
    option_d: '5/4',
    correct_option: 'A',
    explanation: 'For parallel lines, a1/a2 = b1/b2 ≠ c1/c2. Here 3/2 = (2k)/5 ⇒ 2k = 15/2 ⇒ k = 15/4.',
    tags: ['Linear Equations', 'Parallel Lines'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'm10-005',
    exam: 'class_10_cbse',
    subject_id: 'math_10',
    chapter_id: 'math_10_ch4',
    difficulty: 'hard',
    question: 'The discriminant of the quadratic equation 2x² - 4x + 3 = 0 is:',
    option_a: '-8',
    option_b: '10',
    option_c: '-16',
    option_d: '8',
    correct_option: 'A',
    explanation: 'Discriminant D = b² - 4ac. Here a=2, b=-4, c=3. D = (-4)² - 4(2)(3) = 16 - 24 = -8.',
    tags: ['Quadratic Equations', 'Discriminant'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'm10-006',
    exam: 'class_10_cbse',
    subject_id: 'math_10',
    chapter_id: 'math_10_ch5',
    difficulty: 'medium',
    question: 'What is the 11th term of the Arithmetic Progression: -3, -1/2, 2, ...?',
    option_a: '28',
    option_b: '22',
    option_c: '-38',
    option_d: '44',
    correct_option: 'B',
    explanation: 'a = -3, d = -1/2 - (-3) = 5/2. T_11 = a + 10d = -3 + 10(5/2) = -3 + 25 = 22.',
    tags: ['AP', 'nth Term'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 10 CBSE - SCIENCE (science_10) =====================
  {
    id: 's10-001',
    exam: 'class_10_cbse',
    subject_id: 'science_10',
    chapter_id: 'science_10_ch1',
    difficulty: 'easy',
    question: 'Which of the following is a displacement reaction?',
    option_a: 'CaCO3 → CaO + CO2',
    option_b: 'CaO + H2O → Ca(OH)2',
    option_c: 'Fe + CuSO4 → FeSO4 + Cu',
    option_d: '2NaOH + H2SO4 → Na2SO4 + 2H2O',
    correct_option: 'C',
    explanation: 'Fe displaces Cu from CuSO4 because Iron is more reactive than Copper.',
    tags: ['Chemical Reactions', 'Displacement'],
    created_at: new Date().toISOString(),
  },
  {
    id: 's10-002',
    exam: 'class_10_cbse',
    subject_id: 'science_10',
    chapter_id: 'science_10_ch2',
    difficulty: 'medium',
    question: 'Tooth enamel is made up of:',
    option_a: 'Calcium phosphate',
    option_b: 'Calcium carbonate',
    option_c: 'Calcium oxide',
    option_d: 'Calcium sulfate',
    correct_option: 'A',
    explanation: 'Tooth enamel is made of Calcium Phosphate (hydroxyapatite), which is the hardest substance in the human body.',
    tags: ['Acids Bases', 'Enamel'],
    created_at: new Date().toISOString(),
  },
  {
    id: 's10-003',
    exam: 'class_10_cbse',
    subject_id: 'science_10',
    chapter_id: 'science_10_ch3',
    difficulty: 'easy',
    question: 'Which liquid metal exists at room temperature?',
    option_a: 'Sodium',
    option_b: 'Mercury',
    option_c: 'Gallium',
    option_d: 'Potassium',
    correct_option: 'B',
    explanation: 'Mercury (Hg) is the only metal that remains liquid at room temperature (25°C).',
    tags: ['Metals', 'Properties'],
    created_at: new Date().toISOString(),
  },
  {
    id: 's10-004',
    exam: 'class_10_cbse',
    subject_id: 'science_10',
    chapter_id: 'science_10_ch4',
    difficulty: 'medium',
    question: 'The IUPAC name of CH3-CH2-CHO is:',
    option_a: 'Propanol',
    option_b: 'Propanal',
    option_c: 'Propanone',
    option_d: 'Propanoic acid',
    correct_option: 'B',
    explanation: 'CH3-CH2-CHO contains 3 carbon atoms and an aldehyde functional group (-CHO), hence named Propanal.',
    tags: ['Carbon Compounds', 'IUPAC'],
    created_at: new Date().toISOString(),
  },
  {
    id: 's10-005',
    exam: 'class_10_cbse',
    subject_id: 'science_10',
    chapter_id: 'science_10_ch5',
    difficulty: 'easy',
    question: 'The breakdown of pyruvate to give carbon dioxide, water and energy takes place in:',
    option_a: 'Cytoplasm',
    option_b: 'Mitochondria',
    option_c: 'Chloroplast',
    option_d: 'Nucleus',
    correct_option: 'B',
    explanation: 'Aerobic breakdown of pyruvate occurs in Mitochondria, yielding CO2, H2O, and 36-38 ATP molecules.',
    tags: ['Life Processes', 'Respiration'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 10 CBSE - ENGLISH (english_10) =====================
  {
    id: 'e10-001',
    exam: 'class_10_cbse',
    subject_id: 'english_10',
    chapter_id: 'english_10_ch2',
    difficulty: 'easy',
    question: 'Choose the correct form of verb: "She _____ to the market before it started raining."',
    option_a: 'has gone',
    option_b: 'had gone',
    option_c: 'was going',
    option_d: 'went',
    correct_option: 'B',
    explanation: 'The past perfect tense "had gone" expresses an action completed before another past action (started raining).',
    tags: ['Grammar', 'Tenses'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'e10-002',
    exam: 'class_10_cbse',
    subject_id: 'english_10',
    chapter_id: 'english_10_ch3',
    difficulty: 'medium',
    question: 'Change into passive voice: "The chef cooked a delicious meal."',
    option_a: 'A delicious meal was cooked by the chef.',
    option_b: 'A delicious meal is cooked by the chef.',
    option_c: 'A delicious meal has been cooked by the chef.',
    option_d: 'A delicious meal had been cooked by the chef.',
    correct_option: 'A',
    explanation: 'Simple past active voice (cooked) changes to "was/were + past participle" (was cooked) in passive voice.',
    tags: ['Grammar', 'Voice'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 10 CBSE - SOCIAL SCIENCE (social_10) =====================
  {
    id: 'sst10-001',
    exam: 'class_10_cbse',
    subject_id: 'social_10',
    chapter_id: 'social_10_ch1',
    difficulty: 'easy',
    question: 'Who was proclaimed the King of United Italy in 1861?',
    option_a: 'Victor Emmanuel II',
    option_b: 'Kaiser William I',
    option_c: 'Napoleon Bonaparte',
    option_d: 'Giuseppe Garibaldi',
    correct_option: 'A',
    explanation: 'Victor Emmanuel II was proclaimed King of United Italy in 1861 following Italian unification.',
    tags: ['History', 'Nationalism'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'sst10-002',
    exam: 'class_10_cbse',
    subject_id: 'social_10',
    chapter_id: 'social_10_ch3',
    difficulty: 'medium',
    question: 'Which soil is ideal for growing cotton?',
    option_a: 'Alluvial soil',
    option_b: 'Black soil',
    option_c: 'Red soil',
    option_d: 'Laterite soil',
    correct_option: 'B',
    explanation: 'Black soil (Regur soil) is rich in clay and retains moisture, making it ideal for cotton cultivation.',
    tags: ['Geography', 'Resources'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 12 CBSE - PHYSICS (physics_12) =====================
  {
    id: 'p12-001',
    exam: 'class_12_cbse',
    subject_id: 'physics_12',
    chapter_id: 'physics_12_ch1',
    difficulty: 'medium',
    question: 'The electric field strength E due to a point charge q at distance r varies as:',
    option_a: '1/r',
    option_b: '1/r²',
    option_c: 'r',
    option_d: 'r²',
    correct_option: 'B',
    explanation: 'According to Coulomb Law, Electric Field E = k * q / r², following an inverse-square relationship.',
    tags: ['Electrostatics', 'Coulomb Law'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'p12-002',
    exam: 'class_12_cbse',
    subject_id: 'physics_12',
    chapter_id: 'physics_12_ch3',
    difficulty: 'hard',
    question: 'With increase in temperature, the resistivity of a semiconductor:',
    option_a: 'Increases',
    option_b: 'Decreases',
    option_c: 'Remains constant',
    option_d: 'First increases then decreases',
    correct_option: 'B',
    explanation: 'In semiconductors, higher temperature thermally excites covalent bonds, generating free electron-hole pairs and decreasing resistivity.',
    tags: ['Current Electricity', 'Resistivity'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 12 CBSE - CHEMISTRY (chemistry_12) =====================
  {
    id: 'c12-001',
    exam: 'class_12_cbse',
    subject_id: 'chemistry_12',
    chapter_id: 'chemistry_12_ch1',
    difficulty: 'medium',
    question: 'Which law states that partial pressure of gas in vapor phase is proportional to mole fraction of gas in solution?',
    option_a: 'Raoult Law',
    option_b: 'Henry Law',
    option_c: 'Dalton Law',
    option_d: 'Boyale Law',
    correct_option: 'B',
    explanation: 'Henry Law states that p = K_H * x, relating gas solubility/partial pressure to mole fraction in solution.',
    tags: ['Solutions', 'Henry Law'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'c12-002',
    exam: 'class_12_cbse',
    subject_id: 'chemistry_12',
    chapter_id: 'chemistry_12_ch3',
    difficulty: 'hard',
    question: 'The unit of rate constant for a first-order chemical reaction is:',
    option_a: 'mol L⁻¹ s⁻¹',
    option_b: 'L mol⁻¹ s⁻¹',
    option_c: 's⁻¹',
    option_d: 'L² mol⁻² s⁻¹',
    correct_option: 'C',
    explanation: 'For a 1st order reaction, Rate = k[A]. Units: (mol L⁻¹ s⁻¹) = k(mol L⁻¹) ⇒ k has unit s⁻¹ (per second).',
    tags: ['Chemical Kinetics', 'Order of Reaction'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 12 CBSE - BIOLOGY (biology_12) =====================
  {
    id: 'b12-001',
    exam: 'class_12_cbse',
    subject_id: 'biology_12',
    chapter_id: 'biology_12_ch3',
    difficulty: 'easy',
    question: 'The functional unit of inheritance is called a:',
    option_a: 'Chromosome',
    option_b: 'Gene',
    option_c: 'Nucleotide',
    option_d: 'Codon',
    correct_option: 'B',
    explanation: 'A gene is the fundamental physical and functional unit of heredity passed from parents to offspring.',
    tags: ['Genetics', 'Heredity'],
    created_at: new Date().toISOString(),
  },

  // ===================== CLASS 12 CBSE - MATHEMATICS (math_12) =====================
  {
    id: 'm12-001',
    exam: 'class_12_cbse',
    subject_id: 'math_12',
    chapter_id: 'math_12_ch3',
    difficulty: 'medium',
    question: 'If matrix A is symmetric as well as skew-symmetric, then A is a:',
    option_a: 'Diagonal matrix',
    option_b: 'Zero matrix',
    option_c: 'Square matrix',
    option_d: 'Identity matrix',
    correct_option: 'B',
    explanation: 'Symmetric means A = A^T. Skew-symmetric means A = -A^T. Therefore A = -A ⇒ 2A = 0 ⇒ A is a Zero matrix.',
    tags: ['Matrices', 'Properties'],
    created_at: new Date().toISOString(),
  }
];
